### POST LIST
POST http://localhost:8563/lists
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRiOTQyNDllMjk3MTE3M2IwMzkyYTg4In0sImlhdCI6MTY4OTg2ODUxN30.mjKNTqRuK4dZGDI4hkJ7XGWGB0RC6EvihWnx-KEc1p0
Content-Type: application/json

{
    "name": "LIST 11 NEW EDITION"
}

### GET LISTS
GET http://localhost:8563/lists
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRiOTQyNDllMjk3MTE3M2IwMzkyYTg4In0sImlhdCI6MTY4OTg2ODUxN30.mjKNTqRuK4dZGDI4hkJ7XGWGB0RC6EvihWnx-KEc1p0

### GET LIST
GET http://localhost:8563/lists/64b94474a86987ef427e7519
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRiOTQyNDllMjk3MTE3M2IwMzkyYTg4In0sImlhdCI6MTY4OTg2ODUxN30.mjKNTqRuK4dZGDI4hkJ7XGWGB0RC6EvihWnx-KEc1p0

### GET LIST
PATCH http://localhost:8563/lists/64b94474a86987ef427e7519
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRiOTQyNDllMjk3MTE3M2IwMzkyYTg4In0sImlhdCI6MTY4OTg2ODUxN30.mjKNTqRuK4dZGDI4hkJ7XGWGB0RC6EvihWnx-KEc1p0
Content-Type: application/json

{
    "name": "LIST 1 (updated2)"
}

### DELETE TODO
DELETE http://localhost:8563/lists/64b94474a86987ef427e7519
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRiOTQyNDllMjk3MTE3M2IwMzkyYTg4In0sImlhdCI6MTY4OTg2ODUxN30.mjKNTqRuK4dZGDI4hkJ7XGWGB0RC6EvihWnx-KEc1p0
